#pragma once

#include <chaos/StandardHeaders.h>

namespace chaos
{
	class GPUBuffer;
	class GPUBufferPoolEntry;
	class GPUBufferPool;
    class GPUBufferCache;
	class GPUDrawPrimitive;
    class GPUDynamicMesh;
	class GPUFence;
	class GPUFileResource;
	class GPUFramebufferAttachmentInfo;
	class GPUFramebuffer;
	class GPUFramebufferGeneratorAttachmentInfo;
	class GPUFramebufferGenerator;
	class GPUInstancingInfo;
	class GPUMaterialProvider;
	class GPUProgramLoaderCacheOptions;
	class GPUProgram;
	class GPUProgramAction;
	class GPUProgramSetUniformAction;
	class GPUProgramSetAttributeAction;
	//class GPUProgramGetValueAction;
	class GLVariableInfo;
	class GLUniformInfo;
	class GLAttributeInfo;
	class GPUProgramData;
	class GPUProgramGenerator;
	class GPUProgramLoader;
	class GPUProgramProviderBase;
	//class GPUProgramProviderValue;
	class GPUProgramProviderTexture;
	class GPUProgramProvider;
	class GPUProgramProviderChain;
	class GPUProgramSourceGenerator;
	class GPUProgramStringSourceGenerator;
	class GPUProgramFileSourceGenerator;
	class GPUQuery;
	class GPURenderable;
	class GPURenderableFilter;
	//class GPUTypedRenderableFilter;
	class GPURenderableLayerSystem;
	class RenderableLayerInfo;
	class GPURenderbuffer;
	class GPURenderbufferLoader;
	class GPUFramebufferRenderData;
	class GPURenderer;
	class GPUProgramRenderMaterialProvider;
	class GPURenderMaterial;
	class GPURenderMaterialInfo;
	class GPURenderMaterialInfoEntry;
	class GPURenderMaterialParentReference;
	class GPURenderMaterialLoaderReferenceSolver;
	class GPURenderMaterialLoader;
	class GPURenderParams;
	class GPUResourceCallbacks;
	class GPUResourceAutoCallbacks;
	class GPUResource;
	class GPUResourceManagerReloadData;
	class GPUProgramReplaceTextureAction;
	class GPUResourceManager;
	class GPUSimpleMesh;
	class GPUMeshGenerationRequirement;
	class GPUSimpleMeshGenerator;
	//class GPUPrimitiveMeshGenerator;
	class GPUQuadMeshGenerator;
	class GPUTriangleMeshGenerator;
	class GPUCubeMeshGenerator;
	class GPUCircleMeshGenerator;
	class GPUSphereMeshGenerator;
	class GPUSkeletonHierarchyBoneDef;
	class GPUSkeletonHierarchyDef;
	class GPUSkinnedMesh;
	class GPUSkinnedMeshAnimation;
	class GPUSurface;
	class GPUTexture;
	class GPUTextureLoader;
	class GPUVertexArray;
	class GPUVertexArrayCacheEntry;
	class GPUVertexArrayCache;
	class GPUVertexDeclarationEntry;
	class GPUVertexDeclaration;


    class ParticleManager;
    class ParticleAllocationBase;
    class ParticleLayerBase;

}; // namespace chaos

