// BEWARE: this file is generated by premake. do not edit by hand

#pragma once

// kind of project
#define TESTSTATICLIB_IS_STATIC_LIBRARY

// defines an import/export token
#if defined TESTSTATICLIB_IS_SHARED_LIBRARY
#  if defined DEATH_IS_BUILDING_TESTSTATICLIB // are we building the project, or this file is included from external ?
#    define TESTSTATICLIB_API __declspec(dllexport)
#  else
#    define TESTSTATICLIB_API __declspec(dllimport)
#  endif
#else
#  define TESTSTATICLIB_API // no import/export unless for shared library
#endif
