-- =============================================================================
-- ROOT_PATH/executables/MISC
-- =============================================================================

ProcessSubPremake("TestFadeVortexImage")
ProcessSubPremake("TestC++11")
ProcessSubPremake("TestC++17")
ProcessSubPremake("TestAllLibs")
ProcessSubPremake("TestMyZLib")
ProcessSubPremake("TestMyBase64")
ProcessSubPremake("TestOpenCV")
ProcessSubPremake("TestTiledMapReader")
ProcessSubPremake("TestTiledMapParticle")
ProcessSubPremake("TestClientServer")
ProcessSubPremake("TestJSON")
ProcessSubPremake("TestPointers")
ProcessSubPremake("TestJSON2")
ProcessSubPremake("TestOpenFileMap")
ProcessSubPremake("TestFilePathParam")
ProcessSubPremake("TestBoostOptions")
ProcessSubPremake("TestWindowsApp")
ProcessSubPremake("TestCutWord")
ProcessSubPremake("TestAllocator")
ProcessSubPremake("TestBufferPolicy")
ProcessSubPremake("TestScreenshot")
ProcessSubPremake("TestAtlas")
ProcessSubPremake("TestDataSource")
ProcessSubPremake("TestMetaprogramming")
ProcessSubPremake("TestSparseBuffer")
ProcessSubPremake("TestApplication")
ProcessSubPremake("TestInheritanceIntrospection")
ProcessSubPremake("TestSkyBoxLoading")
ProcessSubPremake("TestSkyBoxConversion")
ProcessSubPremake("TestOVR")
ProcessSubPremake("TestTristripper")
ProcessSubPremake("TestCRC32")
ProcessSubPremake("TestRedirectOutput_Console")
ProcessSubPremake("TestRedirectOutput_Windowed")

