-- =============================================================================
-- ROOT_PATH/executables/MISC
-- =============================================================================

build:ProcessSubPremake("Atlas")
build:ProcessSubPremake("BufferPolicy")
build:ProcessSubPremake("ClientServer")
build:ProcessSubPremake("CRC32")
build:ProcessSubPremake("CutWord")
build:ProcessSubPremake("ClassManager")
build:ProcessSubPremake("FadeVortexImage")
build:ProcessSubPremake("GenerateTexture")
build:ProcessSubPremake("JSONTest")
build:ProcessSubPremake("Metaprogramming")
build:ProcessSubPremake("MyBase64")
build:ProcessSubPremake("MyZLib")
build:ProcessSubPremake("OpenCV")
build:ProcessSubPremake("OpenFileMap")
build:ProcessSubPremake("OVR")
build:ProcessSubPremake("RedirectOutput_Console")
build:ProcessSubPremake("Screenshot")
build:ProcessSubPremake("CubeMapConversion")
build:ProcessSubPremake("CubeMapLoading")
build:ProcessSubPremake("SparseBuffer")
build:ProcessSubPremake("WindowsApp")
build:ProcessSubPremake("ConfigurationTest")