-- =============================================================================
-- ROOT_PATH/executables/MISC
-- =============================================================================

ProcessSubPremake("FadeVortexImage")
ProcessSubPremake("C++11")
ProcessSubPremake("C++17")
ProcessSubPremake("AllLibs")
ProcessSubPremake("MyZLib")
ProcessSubPremake("MyBase64")
ProcessSubPremake("OpenCV")
ProcessSubPremake("TiledMapReader")
ProcessSubPremake("TiledMapParticle")
ProcessSubPremake("ClientServer")
ProcessSubPremake("JSON")
ProcessSubPremake("Pointers")
ProcessSubPremake("JSON2")
ProcessSubPremake("OpenFileMap")
ProcessSubPremake("FilePathParam")
ProcessSubPremake("BoostOptions")
ProcessSubPremake("WindowsApp")
ProcessSubPremake("CutWord")
ProcessSubPremake("Allocator")
ProcessSubPremake("BufferPolicy")
ProcessSubPremake("Screenshot")
ProcessSubPremake("Atlas")
ProcessSubPremake("DataSource")
ProcessSubPremake("Metaprogramming")
ProcessSubPremake("SparseBuffer")
ProcessSubPremake("Application")
ProcessSubPremake("InheritanceIntrospection")
ProcessSubPremake("SkyBoxLoading")
ProcessSubPremake("SkyBoxConversion")
ProcessSubPremake("OVR")
ProcessSubPremake("Tristripper")
ProcessSubPremake("CRC32")
ProcessSubPremake("RedirectOutput_Console")
ProcessSubPremake("RedirectOutput_Windowed")

