-- =============================================================================
-- ROOT_PATH/executables/GLFW
-- =============================================================================

build:ProcessSubPremake("Base")
build:ProcessSubPremake("BasicGeometries")
build:ProcessSubPremake("GamepadDetection")
build:ProcessSubPremake("GamepadManager")
build:ProcessSubPremake("ParticleRefactor")
build:ProcessSubPremake("ParticleRefactor2")
build:ProcessSubPremake("Framebuffer")
build:ProcessSubPremake("ResourceFiles")
build:ProcessSubPremake("SimpleTexture")
build:ProcessSubPremake("LoadTexture")
build:ProcessSubPremake("FontTexture")
build:ProcessSubPremake("CubeMap")
build:ProcessSubPremake("MergeCubeMap")
build:ProcessSubPremake("MergeAtlas")
build:ProcessSubPremake("Instancing")
build:ProcessSubPremake("RenderMaterial")
build:ProcessSubPremake("FreeType")
build:ProcessSubPremake("TextureArray")
build:ProcessSubPremake("TextureArrayAtlas")
build:ProcessSubPremake("TextureArrayAnimation")
build:ProcessSubPremake("TextureArrayAtlasSprite")
build:ProcessSubPremake("TextSpriteFormat")
build:ProcessSubPremake("Clocks")
build:ProcessSubPremake("Sound3D")
build:ProcessSubPremake("Spriter")
build:ProcessSubPremake("ViewportWindow")
build:ProcessSubPremake("TestTree27")
build:ProcessSubPremake("KeyboardLayoutConversion")
