// BEWARE: this file is generated by premake. do not edit by hand

#pragma once

// kind of project
#define CHAOS_IS_STATIC_LIBRARY

// defines an import/export token
#if defined CHAOS_IS_SHARED_LIBRARY
#  if defined DEATH_IS_BUILDING_CHAOS // are we building the project, or this file is included from external ?
#    define CHAOS_API __declspec(dllexport)
#  else
#    define CHAOS_API __declspec(dllimport)
#  endif
#else
#  define CHAOS_API // no import/export unless for shared library
#endif
