// BEWARE: this file is generated by premake. do not edit by hand

#pragma once

// kind of project
#define CHAOS2_IS_SHARED_LIBRARY

// defines an import/export token
#if defined CHAOS2_IS_SHARED_LIBRARY
#  if defined DEATH_IS_BUILDING_CHAOS2 // are we building the project, or this file is included from external ?
#    define CHAOS2_API __declspec(dllexport)
#  else
#    define CHAOS2_API __declspec(dllimport)
#  endif
#else
#  define CHAOS2_API // no import/export unless for shared library
#endif
