// BEWARE: this file is generated by premake. do not edit by hand

#pragma once

// kind of project
#define $PROJECT_BUILD_TYPE$

// defines an import/export token
#if defined $PROJECT_NAME$_IS_SHARED_LIBRARY
#  if defined DEATH_IS_BUILDING_$PROJECT_NAME$ // are we building the project, or this file is included from external ?
#    define $PROJECT_NAME$_API __declspec(dllexport)
#  else
#    define $PROJECT_NAME$_API __declspec(dllimport)
#  endif
#else
#  define $PROJECT_NAME$_API // no import/export unless for shared library
#endif
